language: php

sudo: false

php:
  - 7.0

env:
  - WP_VERSION=master WP_MULTISITE=0

before_script:
  - export WP_DEVELOP_DIR=/tmp/wordpress/
  - mkdir -p $WP_DEVELOP_DIR
  - git clone --depth=1 --branch="$WP_VERSION" https://github.com/wordpress/wordpress $WP_DEVELOP_DIR
  - plugin_slug=$(basename $(pwd))
  - plugin_dir=$WP_DEVELOP_DIR/wp-content/plugins/$plugin_slug
  - cd ..
  - mv $plugin_slug $plugin_dir
  - cd $WP_DEVELOP_DIR
  - echo $WP_DEVELOP_DIR
  - cp wp-config-sample.php wp-config.php
  - sed -i "s/database_name_here/wordpress/" wp-config.php
  - sed -i "s/username_here/root/" wp-config.php
  - sed -i "s/password_here//" wp-config.php
  - sed -i "s/example.com/localhost/" $plugin_dir/behat.yml
  - sed -i "s@path/to/wordpress@$WP_DEVELOP_DIR@" $plugin_dir/behat.yml
  - sed -i "s/username:\ admin/username:\ root/" $plugin_dir/behat.yml
  - sed -i "s/password:\ admin/password:\ /" $plugin_dir/behat.yml
  - mysql -e 'CREATE DATABASE wordpress;' -uroot
  - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
  - chmod +x wp-cli.phar
  - mv wp-cli.phar $WP_DEVELOP_DIR/wp
  - export PATH="$WP_DEVELOP_DIR:$PATH"
  - cd $WP_DEVELOP_DIR
  - wp core install --url=localhost --title="Test site" --admin_user="root" --admin_password="" --admin_email="admin@example.net" --skip-email
  - cd $plugin_dir
  - composer install --no-interaction --prefer-source --dev

script:
  - vendor/bin/behat
